cask_args appdir: '/Applications'

tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/versions'
tap 'caskroom/versions'
tap 'michaeldfallen/formula'

brew 'fish'
brew 'bash'
brew 'homebrew/versions/bash-completion2'
brew 'gnu-sed', args: ['with-default-names']
brew 'vim', args: ['override-system-vi']
brew 'homebrew/dupes/apple-gcc42'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/screen'
brew 'coreutils'
brew 'findutils'
brew 'ack'
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'git'
brew 'git-lfs'
brew 'gibo'
brew 'imagemagick', args: ['with-webp']
brew 'lynx'
brew 'lcov'
brew 'openssl'
brew 'testssl'
brew 'thefuck'
brew 'michaeldfallen/formula/git-radar'
# TODO: install through nvm - brew 'node'
brew 'nvm'
brew 'phantomjs'
brew 'gvm'
# TODO: install through gvm - brew 'golang'
brew 'pyenv'
# TODO: install through pyenv - brew 'python'
# TODO: install through pyenv - brew 'python3'
brew 'rbenv'
brew 'ruby-build'
# TODO: install through rbenv - brew 'rbenv'
brew 'jenv'
brew 'phpenv'
# TODO: make sure phpenv-install.sh is run
brew 'php-build'
# TODO: install through phpenv - brew 'homebrew/php/php56', args: ['with-gmp']
brew 'mysql'
brew 'sqlite'
brew 'pass'

cask 'docker'
cask 'vlc'
cask 'skype'
cask 'google-chrome'
cask 'transmission'
cask 'transmit'
cask 'mou'
cask 'dash'
cask 'java'
cask 'virtualbox'
cask 'atom'
cask 'visual-studio-code'
cask 'intellij-idea'
cask 'android-studio'
cask 'pycharm'
cask 'cocoapods'
cask 'sequel-pro'
